README: add note about location for macOS
erikw/restic-automatic-backup-scheduler pull request #95
Opened 2022-05-30 12:42 UTC by adidalal

Just a small update to point out that on M1, the path will be different.

Thanks for putting this together!

2022-05-30 15:01 UTC, erikw requested changes
Thank you for this PR! I was not aware of the change for Apple silicon Macs.

A few changes needed, see individual comments.

2022-05-30 15:01 UTC, erikw commented on README.md
> +	$ source $HOMEBREW_PREFIX/etc/restic/default.env.sh
Ditto

```console
$ source $(brew --prefix)/etc/restic/default.env.sh
```

2022-05-31 00:21 UTC, adidalal commented on README.md
> +1. Fill out [configuration values](#2-configure-b2-credentials-locally) in `$HOMEBREW_PREFIX/etc/restic`.
I use `eval "$(/opt/homebrew/bin/brew shellenv)"` in my profile, but same idea. Updated everywhere

2022-05-31 06:04 UTC, merged

2022-05-31 06:04 UTC, erikw commented
Thanks!